
  CREATE TABLE STUDENT"
   (	"NAME" VARCHAR2(200 BYTE),
	"AGE" NUMBER(10,0),
	"SEX" VARCHAR2(20 BYTE),
	"CLASSID" VARCHAR2(100 BYTE),
	"SID" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	 CONSTRAINT "STUDENT_PK" PRIMARY KEY ("SID")
   )  ;
